### PR TITLE
FixChangePlayerAfterDeath

### PR DESCRIPTION
**Pull request by 9iky6**
Correction of the first call after the death Observer_SetMode player to change the observed Player

### CODE REVIEW

**Comment by 9iky6** [comment]
I did not check the work on linux systems , as it failed to compile by make. But on Windows error did not occur.

Mistake was that when he died a player who is not an administrator , he continued to watch the player who killed him , regardless of the team.

**Comment by xkpx64** [comment]
Too bad it cannot compile on linux

xkp@51-184:~/git/AdminFreeLook-patch-1/support$ make
mkdir -p Release
mkdir -p Release/sdk
make -f /home/xkp/git/AdminFreeLook-patch-1/support/Makefile adminfreelook
make[1]: Entering directory '/home/xkp/git/AdminFreeLook-patch-1/support'
make[1]: *** No rule to make target 'Release/sdk/amxxmodule.o', needed by 'adminfreelook'.  Stop.
make[1]: Leaving directory '/home/xkp/git/AdminFreeLook-patch-1/support'
Makefile:107: recipe for target 'all' failed
make: *** [all] Error 2
xkp@51-184:~/git/AdminFreeLook-patch-1/support$

**Comment by Arkshine** [comment]
Will review/test later, I'm busy for now.

To compile, you need to use AMBuild. Similar to https://wiki.alliedmods.net/Building_AMX_Mod_X.

**Comment by 9iky6** [comment]
cc1plus: ошибка: unrecognized command line option «-std=c++11»
cc1plus: ошибка: некорректный ключ "-Wno-narrowing" [-Werror]
cc1plus: all warnings being treated as errors

**Comment by Arkshine** [comment]
You likely need at least gcc 4.7, but you can also use clang 3.4/3.5, it will compile faster with that.

**Comment by 9iky6** [comment]
In file included from /home/vadim/AdminFreeLook-1.5.4c/public/sdk/amxxmodule.cpp:3030:
/home/vadim/hlsdk/dlls/cbase.h:66:32: error: attribute declaration must precede definition [-Werror]
extern "C" CBASE_DLLEXPORT int GetEntityAPI2( DLL_FUNCTIONS *pFunctionTable, int *interfaceVersion );
                               ^
/home/vadim/AdminFreeLook-1.5.4c/public/sdk/amxxmodule.cpp:2107:17: note: previous definition is here
C_DLLEXPORT int GetEntityAPI2(DLL_FUNCTIONS *pFunctionTable, int *interfaceVersion)
                ^
1 error generated.
Build failed.

gcc 4.9.

**Comment by Arkshine** [comment]
Never tried to compile with gcc-4.9, I'm using only clang 3.4 (same as how AMXX is compiled).

You might need a new rule with `-Wignored-attributes`

**Comment by 9iky6** [comment]
First compiled with the changes were falling server. Then compiled on GCC 4.9 the latest version from here:
https://github.com/Arkshine/AdminFreeLook
And the server also fell . Sigmentacion Fault

https://www.dropbox.com/s/ydkkovj04ncnrbp/adminfreelook_amxx_i386.so?dl=0

It is compiled by me from the repository module , in what could be the problem?
